baseURL = 'https://songdehuacool.github.io/'
languageCode = 'en-us'
title = 'songdehua blog'
theme = 'ananke'

[menu]
[[menu.main]]
  name = '首页'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Hugo学习'          # 名字
  url = '/series/learn-hugo' # 跳转链接
  weight = 2                 # 权重, 越低位置越前